import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, team, bhanu }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-3 min-h-screen text-white text-center items-center">
          <div className="bg-neutral -800">{children}</div>
          <div className="bg-zinc-700">{team}</div>
          <div className="bg-slate-800">{bhanu}</div>
        </div>
      </body>
    </html>
  );
}

/* 
import { checkUserRole } from '@/lib/auth'
 
export default function Layout({ user, admin }) {
  const role = checkUserRole()
  return role === 'admin' ? admin : user   // showing diff page
}
*/
