import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  userdata,
}: Readonly<{
  children: React.ReactNode;
  userdata: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          {/* Main content area */}
          <div className="flex-1">{children}</div>
          {/* Parallel route slot for user data */}
          <div className="w-1/3 border-l border-gray-200 dark:border-gray-800">
            {userdata}
          </div>
        </div>
      </body>
    </html>
  );
}
