import { Allura } from 'next/font/google';
import './globals.css';

const allura = Allura({
  variable: '--font-allura',
  subsets: ['latin'],
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${allura.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
